/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fatec.poo.view;

import fatec.poo.control.DaoConsulta;
import fatec.poo.control.DaoExame;

import fatec.poo.control.PreparaConexao;
import fatec.poo.model.Consulta;
import fatec.poo.model.Exame;
import fatec.poo.model.Medico;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;


/**
 *
 * @author pietr
 */
public class GuiExame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GuiExame.class.getName());

    /**
     * Creates new form GuiExame
     */
    public GuiExame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnConsultarMedico = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtCodConsulta = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        txtHorario = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        jFormattedTxtData = new javax.swing.JFormattedTextField();
        btnConsultar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblNomeMedico = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Marcar Exame");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Código");

        jLabel2.setText("Código Consulta");

        jLabel3.setText("Descrição");

        jLabel4.setText("Data:");

        jLabel5.setText("Horário");

        jLabel6.setText("Valor");

        btnConsultarMedico.setText("jButton1");
        btnConsultarMedico.setEnabled(false);
        btnConsultarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarMedicoActionPerformed(evt);
            }
        });

        jLabel7.setText("Médico");

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        txtCodConsulta.setEnabled(false);

        txtDescricao.setEnabled(false);

        txtHorario.setEnabled(false);

        txtValor.setEnabled(false);

        try {
            jFormattedTxtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTxtData.setEnabled(false);

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/save.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lblNomeMedico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblNomeMedico.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTxtData, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodigo)
                                    .addComponent(txtCodConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(btnConsultarMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(lblNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnInserir)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtValor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                        .addComponent(txtHorario, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(132, 132, 132)
                                .addComponent(btnExcluir)
                                .addGap(28, 28, 28)
                                .addComponent(btnSair))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConsultar)
                        .addGap(148, 148, 148)
                        .addComponent(btnAlterar)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(btnConsultarMedico)
                        .addComponent(jLabel7)
                        .addComponent(txtCodConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTxtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarMedicoActionPerformed
       int codConsulta = Integer.parseInt(txtCodConsulta.getText());
    
    
    consulta = daoConsulta.consultar(codConsulta);

    if (consulta == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Consulta não cadastrada");
        txtCodConsulta.requestFocus();
    } else {
       
         lblNomeMedico.setText(consulta.getMedico().getNome());
        
        txtCodConsulta.setEnabled(false);
        btnConsultarMedico.setEnabled(false); 
        
       
        txtDescricao.setEnabled(true);
        jFormattedTxtData.setEnabled(true);
        txtHorario.setEnabled(true);
        txtValor.setEnabled(true);
        
        btnInserir.setEnabled(true);
        txtDescricao.requestFocus();
    }

    }//GEN-LAST:event_btnConsultarMedicoActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        if (txtCodigo.getText().isEmpty()) return;
            
            
            exame = daoExame.consultar(Integer.parseInt(txtCodigo.getText()));
    
            if(exame == null){
               
                txtCodConsulta.setEnabled(true);
                btnConsultar.setEnabled(true);
                txtCodConsulta.requestFocus();
                
                
                lblNomeMedico.setText("");
                txtDescricao.setText("");
                jFormattedTxtData.setText("");
                txtHorario.setText("");
                txtValor.setText("");
                
                
                btnConsultarMedico.setEnabled(true);
                btnConsultar.setEnabled(false);
                btnInserir.setEnabled(false); 
                
            } else {
               
                
               
                int idConsulta = exame.getConsulta().getCodigo();
                consulta = daoConsulta.consultar(idConsulta);
                
 
                txtCodConsulta.setText(String.valueOf(consulta.getCodigo()));
                txtDescricao.setText(exame.getDescricao());
                jFormattedTxtData.setText(exame.getData());
                txtHorario.setText(exame.getHorario());
                txtValor.setText(String.valueOf(exame.getValor()));
                
               
                if (consulta.getMedico() != null) {
                    lblNomeMedico.setText(consulta.getMedico().getNome());
                } else {
                    lblNomeMedico.setText("Médico não encontrado");
                }
                
                
                txtCodigo.setEnabled(false);
                txtCodConsulta.setEnabled(false);
                btnConsultar.setEnabled(false);
                
                txtDescricao.setEnabled(true);
                jFormattedTxtData.setEnabled(true);
                txtHorario.setEnabled(true);
                txtValor.setEnabled(true);
                
                btnConsultar.setEnabled(false);
                btnInserir.setEnabled(false);
                btnAlterar.setEnabled(true);
                btnExcluir.setEnabled(true);
            }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        exame = new Exame(Integer.parseInt(txtCodigo.getText()), txtDescricao.getText());
        exame.setDescricao(txtDescricao.getText());
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
LocalDate data = LocalDate.parse(jFormattedTxtData.getText(), formato);
        exame.setData(data.format(formato));
        exame.setHorario(txtHorario.getText());
        exame.setValor(Double.parseDouble(txtValor.getText()));
        consulta.addExame(exame);
        daoExame.inserir(exame);
        
        
         txtCodigo.setText("");
         txtCodConsulta.setText("");
         txtDescricao.setText("");
         jFormattedTxtData.setText("");
         txtHorario.setText("");
         txtValor.setText("");
         lblNomeMedico.setText("");
         
         txtCodigo.setEnabled(true);
         txtCodConsulta.setEnabled(false);
         btnConsultarMedico.setEnabled(false);
    
    txtDescricao.setEnabled(false);
    jFormattedTxtData.setEnabled(false);
    txtHorario.setEnabled(false);
    txtValor.setEnabled(false);
    
    btnConsultar.setEnabled(true);
    btnInserir.setEnabled(false);
    txtCodigo.requestFocus();
    }//GEN-LAST:event_btnInserirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       prepCon = new PreparaConexao("","");
    prepCon.setDriver("net.ucanaccess.jdbc.UcanaccessDriver");
    
    
    prepCon.setConnectionString("jdbc:ucanaccess://C:\\Users\\artur\\ProjetoPOO\\prjPOOPietroArturAna\\src\\fatec\\poo\\basededados\\BDClinica.accdb");
    
    daoConsulta = new DaoConsulta(prepCon.abrirConexao());
    daoExame = new DaoExame(prepCon.abrirConexao());
    }//GEN-LAST:event_formWindowOpened

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
         if (JOptionPane.showConfirmDialog(null, "Confirma Alteração?")== 0){
             exame.setDescricao(txtDescricao.getText());
             exame.setHorario(txtHorario.getText());
             exame.setValor(Double.parseDouble(txtValor.getText()));
             exame.setData(jFormattedTxtData.getText());
             consulta.addExame(exame);
             daoExame.alterar(exame);
         }
        txtCodigo.setText("");
        txtCodConsulta.setText("");
        txtDescricao.setText("");
        jFormattedTxtData.setText("");
        txtHorario.setText("");
        txtValor.setText("");
        lblNomeMedico.setText(""); 
        
        
        txtCodConsulta.setEnabled(false);
        btnConsultarMedico.setEnabled(false); 
        txtDescricao.setEnabled(false);
        jFormattedTxtData.setEnabled(false);
        txtHorario.setEnabled(false);
        txtValor.setEnabled(false);
        
       
        txtCodigo.setEnabled(true);
        
        
        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        
        
        txtCodigo.requestFocus();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Exclusão?") == 0){
            daoExame.excluir(exame);
            txtCodigo.setText(null);
            txtCodConsulta.setText(null);
            txtDescricao.setText(null);
            jFormattedTxtData.setText(null);
            txtHorario.setText(null);
            txtValor.setText(null);
            lblNomeMedico.setText(null); 
        
        
        txtCodConsulta.setEnabled(false);
        btnConsultarMedico.setEnabled(false); 
        txtDescricao.setEnabled(false);
        jFormattedTxtData.setEnabled(false);
        txtHorario.setEnabled(false);
        txtValor.setEnabled(false);
        
       
        txtCodigo.setEnabled(true);
        
        
        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        
        
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
           prepCon.fecharConexao();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnConsultarMedico;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JFormattedTextField jFormattedTxtData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblNomeMedico;
    private javax.swing.JTextField txtCodConsulta;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtHorario;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
    private PreparaConexao prepCon=null;
    private Exame exame = null;
    private DaoExame daoExame = null;
    private Consulta consulta = null;
    private DaoConsulta daoConsulta = null;
}
